config/routes.rb
Rails.application.routes.draw do
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :username, presence: true, length: { within: 3..24 }, uniqueness: true
	validates :email, presence: true, uniqueness: true
	has_secure_password
	validates :password, presence: true, length: { within: 6..30 }
	has_many :posts

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
			# self.update_attribute(:remember_token, User.digest(remember_token))
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :is_signed_in?, only: [:new, :create]

	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			flash[:success] = "Post sucessfully made"
			redirect_to root_path
		else
			flash[:error] = "Post failed to be made"
			render 'new'
		end
	end

	def is_signed_in?
		unless signed_in?
			redirect_to login_path
		end
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :user_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			flash[:success] = "Succesfully logged in"
			sign_in user
			redirect_to root_path
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
  	remember_token = User.new_remember_token
  	cookies.permanent[:remember_token] = remember_token
  	user.update_attribute(:remember_token, User.digest(remember_token))
  	self.current_user = user
  end

  def current_user=(user)
  	@current_user = user
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  # I don't get it. apparently current_user wasn't being called to maek sure an inital user was stored in @current_user?
  def signed_in?
  	current_user
  	!@current_user.nil?
  end

  def sign_out
  	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
  	cookies.delete(:remember_token)
  	self.current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
 <% end %>

<% if signed_in? %>
	<h2><%= current_user.username %></h2>
	<%= link_to "Log out", logout_path, method: 'delete', :confirm => "Sure? A bunny will die" %>
<% else %>
	<%= link_to "Login", login_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>All posts</h1>
<% if signed_in? %>
	<%= link_to "Create a post", new_post_path %>
<% end %>

<% @posts.each do |post| %>
	<h3><%= post.title %></h3>
	<% if signed_in? %>
		<h4>Posted by: <%= post.user.username %></h4>
	<% end %>
	<p><%= post.body %></p>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title, placeholder: "Insert title here" %><br />
	<%= f.label :body %>
	<%= f.text_area :body, placeholder: "Insert text here" %><br />
	<%= f.submit "submit" %>
<% end %>